name: learn_github_workshop
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, workflow_dispatch]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  ahoj_svete:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo Ahoj,
          echo vsemocny svete
  need_job:
    needs: ahoj_svete
    runs-on:  ubuntu-latest
    steps:
      - name: need job
        run: echo Nespustim se dokud nedobehne ahoj_svete
  need_job2:
    needs: [check-bats-version, ahoj_svete, need_job]
    runs-on:  ubuntu-latest
    steps:
      - name: need job2
        run: |
          echo Nespustim se dokud nedobehne pole 
          echo "${{ toJSON(needs) }}"
  need_job3:
    if: ${{ github.triggering_actor == 'procesor2017' }}
    needs: need_job2
    runs-on: ubuntu-latest
    steps:
      - name: if trigger procesor
        run: echo Triggnul mě "${{ github.triggering_actor }}"
  secret:
    runs-on: ubuntu-latest
    env:
    steps:
      - name: vypis secret
        run: echo ${{ secrets.MY_NAME }}
