name: learn_github_workshop
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, workflow_dispatch]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  ahoj_svete:
    runs-on: ubuntu-latest
    steps:
      - name: Ahoj_svete
      - run: |
          echo "Hello World"
